In [1]:
import torch

from linear_operator.utils.cholesky import psd_safe_cholesky


# ランダムな対称半正定値行列を作成する関数
def create_psd_matrix(n, eps=1e-6):
    # ランダム行列を生成
    A = torch.randn(n, n)
    # 行列を転置したものと掛け合わせて対称な半正定値行列を作成
    psd_matrix = A @ A.T
    # 安定性を確保するために、対角成分に小さな値を足して調整
    psd_matrix += eps * torch.eye(n)
    return psd_matrix

# 行列サイズ
n = 5

# 半正定値行列を生成
psd_matrix = create_psd_matrix(n)
print("PSD Matrix:\n", psd_matrix)

# psd_safe_choleskyでコレスキー分解を実行
cholesky_factor = psd_safe_cholesky(psd_matrix)
print("\nCholesky Factor:\n", cholesky_factor)

# コレスキー因子の確認 (元の行列に戻るか)
reconstructed_matrix = cholesky_factor @ cholesky_factor.T
print("\nReconstructed Matrix:\n", reconstructed_matrix)

PSD Matrix:
 tensor([[ 6.1761, -1.3650,  3.6816, -2.8672, -0.0192],
        [-1.3650,  6.2892, -3.4966,  0.5021,  2.0294],
        [ 3.6816, -3.4966,  8.2755, -0.4768, -3.0200],
        [-2.8672,  0.5021, -0.4768,  2.0223, -0.3332],
        [-0.0192,  2.0294, -3.0200, -0.3332,  8.0212]])

Cholesky Factor:
 tensor([[ 2.4852,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.5493,  2.4469,  0.0000,  0.0000,  0.0000],
        [ 1.4814, -1.0964,  2.2088,  0.0000,  0.0000],
        [-1.1537, -0.0538,  0.5313,  0.6373,  0.0000],
        [-0.0077,  0.8276, -0.9513,  0.3260,  2.5150]])

Reconstructed Matrix:
 tensor([[ 6.1761, -1.3650,  3.6816, -2.8672, -0.0192],
        [-1.3650,  6.2892, -3.4966,  0.5021,  2.0294],
        [ 3.6816, -3.4966,  8.2755, -0.4768, -3.0200],
        [-2.8672,  0.5021, -0.4768,  2.0223, -0.3332],
        [-0.0192,  2.0294, -3.0200, -0.3332,  8.0212]])
